@VideoGameCatalog.API_HostAddress = http://localhost:5135

### Get all video games
GET {{VideoGameCatalog.API_HostAddress}}/api/videogames
Accept: application/json

###

### Get a single game by ID
GET {{VideoGameCatalog.API_HostAddress}}/api/videogames/1
Accept: application/json

###

### Create a new game
POST {{VideoGameCatalog.API_HostAddress}}/api/videogames
Content-Type: application/json

{
  "title": "Test Game",
  "genre": "RPG",
  "releaseDate": "2022-01-01"
}

###

### Update an existing game
PUT {{VideoGameCatalog.API_HostAddress}}/api/videogames/1
Content-Type: application/json

{
  "id": 1,
  "title": "Updated Game",
  "genre": "Action",
  "releaseDate": "2023-05-01"
}
